### PR TITLE
Fixed API Version for Prometheus Kind

### PR DESCRIPTION
**Pull request by jpkrohling**

### CODE REVIEW

**Comment by jpkrohling** [comment]
I think @kevinearls had a similar issue.

**Comment by jpkrohling** [comment]
Actually, it was @jmazzitelli who first ran into this.

**Comment by objectiser** [comment]
@jpkrohling Thanks!

**Comment by objectiser** [comment]
@jmazzitelli Thanks for spotting this.

**Comment by theute** [comment]
Breaks for OpenShift now, because we need to use an older version of OpenShift (3.6.0-alpha2) of another issue :-/

**Pull request merged**
