### PR TITLE
Adjusted the Jaeger Agent service name

### PR DESCRIPTION
**Pull request by jpkrohling**

### CODE REVIEW

**Comment by objectiser** [comment]
@jpkrohling The top level Kubernetes.md instructions will also need to be updated to:
`minikube service jaeger-query --url`

**Comment by objectiser** [comment]
@jpkrohling works well - so just needs the one change to the Kubernetes.md and it is good to go.

**Comment by jpkrohling** [comment]
Updated.

**Comment by objectiser** [comment]
@jpkrohling Just to check, was the `JAEGER_REPORTER_LOG_SPANS` env var just added, or was it there before (and I missed it)?

**Comment by objectiser** [comment]
@jpkrohling nevermind - found it in the local version I tested.

**Comment by jpkrohling** [comment]
I just added it, I think it's easier to debug networking issues if we know that the tracer ACKs the span.

**Comment by objectiser** [comment]
@jpkrohling Thanks!

**Pull request merged**
